### ISSUE TITLE
Mail Hide 2 issue

### ISSUE THREAD

**Issue by jimfromsd** [hanshuo/mailhide2#2]
Shuo, I have tried to apply your changes, but I keep getting "ERROR for site owner: Invalid site key". I tried creating new ReCAPTCHA keys for the site and have tried using both versions of the keys in both versions, regular and invisible, but I still cannot get this to work. The pages are http://www.magicbeyondimagination.com/contact_invisible.html and http://www.magicbeyondimagination.com/contact_test.html. Not sure what I am doing wrong. Any suggestions would be greatly appreciated. Thanks.

**Comment by hanshuo** [comment]
Looks like you did not use the correct keys. A reCAPTCHA v2 key cannot be both regular and invisible. Get a new key pair through Google, and make sure to include your site in the "Domains" of the "Key Settings". Keep in mind that your old reCAPTCHA v1 key will not work.

**Comment by jimfromsd** [comment]
Attaching an image showing contents of files and error message. I even added the word "the" to differentiate from original email.html. Still error.

![error1](https://user-images.githubusercontent.com/42217023/43857380-ff6ae9fe-9aff-11e8-8c95-82e75addd373.jpg)

**Comment by hanshuo** [comment]
Remove the angle brackets from your keys.

**Comment by jimfromsd** [comment]
That fixed the error message but when I now click the "... not a robot box, I get another error message that I failed. This was on a PC. The website owner said he got pictures to describe but I went straight to an error message. He was using an IPhone. I will try it on my Android. We are making progress at least. Thanks.

**Comment by jimfromsd** [comment]
Tried it on my Android phone using Chrome. Checked the box, clicked Reveal the email address and got "Failed the Recaptcha test".

**Comment by hanshuo** [comment]
Replace line 15 of `email.php` with the following to reveal the error code: 

`echo '<p>You failed the reCAPTCHA test. (Error code: ' . $responseKeys["error-codes"] . ')</p> <button onclick=\"history.go(-1);\">Back </button>';`

Post the error code and a screenshot of your `email.php` as you did previously.

**Comment by jimfromsd** [comment]
Looks like blank error code...
![email_error2](https://user-images.githubusercontent.com/42217023/43931727-e04a7896-9bf4-11e8-90bf-203f38307e28.jpg)

**Comment by hanshuo** [comment]
Insert the following after line 12, and post the result: 

`var_dump($responseKeys);`

**Comment by jimfromsd** [comment]
OK, we got something (nothing, actually, but I guess NULL has some significance...)
![email_error3](https://user-images.githubusercontent.com/42217023/43974059-3055f786-9c8e-11e8-888d-711ed51fddd6.jpg)

**Comment by hanshuo** [comment]
This is likely because your PHP server settings had `allow_url_fopen` disabled, which made `file_get_contents` return nothing. See the discussions on this page for an alternative solution using `curl`:

https://gist.github.com/jonathanstark/dfb30bdfb522318fc819

**Comment by jimfromsd** [comment]
This is getting a little over my head, as my PHP knowledge is admittedly limited. I have spoken with the website owner and I found a simpler method using JavaScript. Thanks for all your help, though.
